index:
  path: /
  controller: App\Controller\DefaultController::index

app_login:
  path: /login
  controller: App\Controller\SecurityController::login

app_logout:
  path: /logout
  controller: App\Controller\SecurityController::logout

user_index:
  path: /user_index
  controller: App\Controller\UserController::index

user_show:
  path: /user_show/{id}
  controller: App\Controller\UserController::show

user_new:
  path: /user_new
  controller: App\Controller\UserController::new

#user_update:
#  path: /user_update
#  controller: App\Controller\SecurityController::userDelete
#  methods: GET